/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 coca.gltf --transform
Author: sloth (https://sketchfab.com/slothx2w)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coca-cola-soda-can-762794c155b84267a906c29507322734
Title: Coca Cola Soda Can
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) { 
  const group = useRef()
  const { nodes, materials } = useGLTF('./coca-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={89.14}>
          <mesh geometry={nodes.Body_Wrap_0.geometry} material={materials.Wrap} />
          <mesh geometry={nodes.Body_Metalic_0.geometry} material={materials.Metalic} />
        </group>
        <mesh geometry={nodes.Cap_Metalic_0.geometry} material={materials.Metalic} position={[0, 393.62, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Opening_Metalic_0.geometry} material={materials.Metalic} position={[0, 400.46, -10.24]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('./coca-transformed.glb')
