/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 iphone.gltf --transform
Author: atomle (https://sketchfab.com/atomle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-11-558b8e99bbd4483b9bb2182d8dc72de2
Title: Iphone 11
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/iphone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.55}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.uLlchpMvpZkYYdr.geometry} material={materials.YmmlbdYKWWpsbpf} />
          <mesh geometry={nodes.PTGmOSMeLgPMlHb.geometry} material={materials.dgrLaHFnkuUTCxT} />
          <mesh geometry={nodes.sKfIrMOQJBaCNTb.geometry} material={materials.ImsThapiChVnSLY} />
          <mesh geometry={nodes.NqXOuTrdCTmXmwx.geometry} material={materials.rjZBcwgXmeNssMr} />
          <mesh geometry={nodes.oEdHjvigCkZzkJW.geometry} material={materials.daWPeTsFgjqatVY} />
          <mesh geometry={nodes.qdLrdTePVyopEiX.geometry} material={materials.ImsThapiChVnSLY} />
          <mesh geometry={nodes.krIyFILqpSozfKb.geometry} material={materials.hrISjdoefWkTgAm} />
          <mesh geometry={nodes.OwpeTDmqbJCwjSp.geometry} material={materials.jahfiZGcfVShWwc} />
          <mesh geometry={nodes.okAtguQexaUNCHu.geometry} material={materials.jahfiZGcfVShWwc} />
          <mesh geometry={nodes.tlqSFgGqPCTunvF.geometry} material={materials.OtTboXcDLUyYbgB} />
          <mesh geometry={nodes.FGEknTFvKtOABPA.geometry} material={materials.rjZBcwgXmeNssMr} />
          <mesh geometry={nodes.NIKLXLthXklDxap.geometry} material={materials.lAnurazBaSrgctP} />
          <mesh geometry={nodes.ULmJERpLHoveHVK.geometry} material={materials.ziZYLnkoumiTQun} />
          <mesh geometry={nodes.TtpLqgRSQxQynSH.geometry} material={materials.ImsThapiChVnSLY} />
          <mesh geometry={nodes.dzKinPfztMLTAdT.geometry} material={materials.hrISjdoefWkTgAm} />
          <mesh geometry={nodes.MwxtCHUYxbWEOny.geometry} material={materials.rjZBcwgXmeNssMr} />
          <mesh geometry={nodes.XZlLnuGHRUhjWYg.geometry} material={materials.daWPeTsFgjqatVY} />
          <mesh geometry={nodes.zXQPUIbziazBYki.geometry} material={materials.rjZBcwgXmeNssMr} />
          <mesh geometry={nodes.vYOsmhAGpjeZjnz.geometry} material={materials.daWPeTsFgjqatVY} />
          <mesh geometry={nodes.VauIPWIJgyQhpBQ.geometry} material={materials.rjZBcwgXmeNssMr} />
          <mesh geometry={nodes.YsuKTsNdUVKCqTj.geometry} material={materials.daWPeTsFgjqatVY} />
          <mesh geometry={nodes.HuFgkStJdkIZIfJ.geometry} material={materials.uYkxRuVXsETgcDZ} />
          <mesh geometry={nodes.wJrsQGjWUtMnoCY.geometry} material={materials.kwzRnYDwxrnKgVV} />
          <mesh geometry={nodes.bctNUknTTpawOZT.geometry} material={materials.dgrLaHFnkuUTCxT} />
          <mesh geometry={nodes.ZLEIiCkKopMPgPM.geometry} material={materials.ImsThapiChVnSLY} />
          <mesh geometry={nodes.KOLAoCVtgKuMVKs.geometry} material={materials.NVpZoGrBUhfXCoo} />
          <mesh geometry={nodes.SXmcYJMCrdOwkhf.geometry} material={materials.hrISjdoefWkTgAm} />
          <mesh geometry={nodes.LxgMKIkeHZhyOSB.geometry} material={materials.UKcVVyjRJKyQpxF} />
          <mesh geometry={nodes.FnYekyDeIgWRgcR.geometry} material={materials.TUrpJVgwidkmkOs} />
          <mesh geometry={nodes.aLCSeOzJnxilzDx.geometry} material={materials.QAroVnkuqbkvbRi} />
          <mesh geometry={nodes.tBcMvERRaHyKOpF.geometry} material={materials.uoUyWEWEzpyeWDt} />
          <mesh geometry={nodes.dGoJrbgiIXYfJjg.geometry} material={materials.HeITATdTtCnXcQK} />
          <mesh geometry={nodes.VsMZsGeFfZFQTmc.geometry} material={materials.iqBhVDhZFwZMJQW} />
          <mesh geometry={nodes.vFGdPjXCpKOyArK.geometry} material={materials.zxfwxKHwauVfXRZ} />
          <mesh geometry={nodes.wSDVfPzCkimFXLT.geometry} material={materials.cpCRQJEjwskJfrh} />
          <mesh geometry={nodes.rgasndSJTKUFYEl.geometry} material={materials.GxwCmSgPoHeWcJP} />
          <mesh geometry={nodes.QqyyZlzeAtLCUiz.geometry} material={materials.XQgLyqgSmnudXQJ} />
          <mesh geometry={nodes.HeqeZnwBJeGdpzO.geometry} material={materials.ZOYWNbjtwJBLgbf} />
          <mesh geometry={nodes.CLQBCaNULGDIhqH.geometry} material={materials.ymzWHUdxAtfTJpO} />
          <mesh geometry={nodes.zqSNuzFsYmLIdPw.geometry} material={materials.duwmJxEFoSznaIG} />
          <mesh geometry={nodes.wVAKRufItfGHztK.geometry} material={materials.oqOsVyiRysdSFdN} />
          <mesh geometry={nodes.KurtsXgdmQwQOCh.geometry} material={materials.ImsThapiChVnSLY} />
          <mesh geometry={nodes.uwqqyOSTObjTlPI.geometry} material={materials.duQyXwGlcbqjSRP} />
          <mesh geometry={nodes.jkCCgiJMyWISmbG.geometry} material={materials.fKEoCdQvihFwZXf} />
          <mesh geometry={nodes.jDNegZKkKtVFfpc.geometry} material={materials.rjZBcwgXmeNssMr} />
          <mesh geometry={nodes.TjixwblguJPgLCW.geometry} material={materials.AmkcDMuNFMlbukQ} />
          <mesh geometry={nodes.YiBcsSRBRProMfi.geometry} material={materials.ImsThapiChVnSLY} />
          <mesh geometry={nodes.LFlZqlQODedKCII.geometry} material={materials.duQyXwGlcbqjSRP} />
          <mesh geometry={nodes.kjRRBQNGNAfFnNW.geometry} material={materials.fKEoCdQvihFwZXf} />
          <mesh geometry={nodes.xEbpGfhWNAYIhky.geometry} material={materials.rjZBcwgXmeNssMr} />
          <mesh geometry={nodes.OvFzTgftwRDDSDo.geometry} material={materials.AmkcDMuNFMlbukQ} />
          <mesh geometry={nodes.QMjSPPkuyrvNzLA.geometry} material={materials.ImsThapiChVnSLY} />
          <mesh geometry={nodes.jpPWoKPJzucntvc.geometry} material={materials.fKEoCdQvihFwZXf} />
          <mesh geometry={nodes.XFbtoSYqOTtGCkp.geometry} material={materials.AmkcDMuNFMlbukQ} />
          <mesh geometry={nodes.QBMkTKYwpOYQjWt.geometry} material={materials.hrISjdoefWkTgAm} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/iphone-transformed.glb')
